### PR TITLE
Add icon and desktop file

### LINKED ISSUE #10: add a .desktop file in /usr/share/applications so it can be shown in a menu
add a . desktop file.
and an icon.
ao it can be launched from menu.

### PR DESCRIPTION
**Pull request by cyclopsian**
Fixes #10

### CODE REVIEW

**Comment by ReekyMarko** [comment]
Can we get this merged?

**Comment by cyclopsian** [comment]
@ReekyMarko Are you able to test this branch? I will merge if someone besides me tests and doesn't notice any issues. Please also mention your distro and compositor you tested with, if you feel like it.

**Comment by ReekyMarko** [comment]
I've been using it since yesterday on Sway, distro is Arch Linux. It launches fine but I think the icon needs to be added to the AUR PKGBUILD, as I just switched the source to this branch and no icon is shown in rofi.

But other than that, it's ready to be merged. It's up to the AUR maintainer to add the icon.

**Comment by somini** [comment]
Can confirm that dropping the correct file on the user-equivalent directories works. Gets picked up by rofi at least, seems to follow the spec.

- `.desktop` file in `~/.local/share/applications` (based on `resources/wdisplays.desktop.in`)
   - The system location would be `/usr/share/applications`
- Icon `resources/wdisplays.svg` in `~/.local/share/icons/hicolor/apps/wdisplays.svg`
   - The system location would be `/usr/share/icons/hicolor/apps`

**Comment by cyclopsian** [comment]
I just tested it with rofi too, looks good. Merging.

**Pull request merged**
